### ISSUE TITLE
I cannot export under GNU/Linux

### ISSUE THREAD

**Issue by YorozuyaDev** [renpy/renpyweb#3] opened 2020-01-28 20:31 UTC
I am using Arch Linux, current version of python 3.8 , when I try to compile to web, it gives following error:
```
I'm sorry, but an uncaught exception occurred.


While running game code:

File "game/web.rpy", line 205, in <module>

File "game/web.rpy", line 103, in build_web

IOError: [Errno 32] Broken pipe


-- Full Traceback ------------------------------------------------------------


Full traceback:

File "launcher/game/web.rpyc", line 205, in script

File "/home/yorozuya3/renpy-7.3.5-sdk/renpy/ast.py", line 914, in execute

renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)

File "/home/yorozuya3/renpy-7.3.5-sdk/renpy/python.py", line 2028, in py_exec_bytecode

exec bytecode in globals, locals

File "game/web.rpy", line 205, in <module>

File "game/web.rpy", line 103, in build_web

File "webserver.py", line 241, in start

File "/home/yorozuya3/renpy-7.3.5-sdk/renpy/log.py", line 235, in write

self.real_file.flush()

IOError: [Errno 32] Broken pipe


Linux-4.19.98-1-lts-x86_64-with-glibc2.2.5

Ren'Py 7.3.5.606

Ren'Py Launcher 7.3.5.606

Tue Jan 28 19:40:20 2020
```

**Comment by Beuc** [comment] 2020-01-28 22:39
Hi and thanks for reporting the bug.

I cannot reproduce the issue.
It seems the "Broken pipe" Python error generally occurs in corner cases when doing redirections - are you redirecting stdin/stdout/stderr when running Ren'Py?

Also, Ren'Py comes bundled with Python 2.7, which is used automatically. I know there's an effort to support Python 3 gracefully (so old games still work) but right now only Python 2 is supported.

**Comment by YorozuyaDev** [comment] 2020-01-29 01:18
Ok, It works in other computer, with same GNU/Linux distro etc so it's seems to be a "local" problem

**Comment by Beuc** [comment] 2020-01-29 10:17
OK, I'm closing the issue.

**Closed by Beuc** 2020-01-29 10:17 UTC
